# ==========================================================
# 📄 BaseCVTemplate.py
# Predefined ATS-friendly resume layout for Stage 3
# ==========================================================

import os
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, HRFlowable,
    ListFlowable, ListItem
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle


# Fixed section order for ATS-friendly resumes
SECTION_ORDER = ["CONTACT", "SUMMARY", "SKILLS", "PROJECTS", "EXPERIENCE", "EDUCATION"]


def build_cv_from_data(candidate_data: dict, sections: dict, output_pdf_path: str):
    """
    Builds a one-page, ATS-friendly resume PDF using a fixed layout.
    candidate_data: dict containing name, email, phone, location, etc.
    sections: dict of resume sections generated by LLaMA.
    output_pdf_path: final PDF path to save.
    """

    os.makedirs(os.path.dirname(output_pdf_path), exist_ok=True)

    # --- Initialize PDF Document ---
    doc = SimpleDocTemplate(
        output_pdf_path,
        pagesize=A4,
        topMargin=0.6 * inch, bottomMargin=0.6 * inch,
        leftMargin=0.8 * inch, rightMargin=0.8 * inch
    )

    # --- Define Styles ---
    styles = getSampleStyleSheet()
    header_style = ParagraphStyle(
        "Header", parent=styles["Heading1"],
        fontSize=22, leading=26, alignment=1,
        textColor=colors.HexColor("#0B3D91"), spaceAfter=6
    )
    section_title = ParagraphStyle(
        "SectionTitle", parent=styles["Heading2"],
        fontSize=13, leading=16, spaceBefore=10, spaceAfter=4,
        textColor=colors.HexColor("#1A1A1A")
    )
    body_style = ParagraphStyle(
        "BodyText", parent=styles["Normal"],
        fontSize=11, leading=15, spaceAfter=4
    )

    story = []

    # ----------------------------------------------------------
    # 🧾 HEADER
    # ----------------------------------------------------------
    name = candidate_data.get("name") or candidate_data.get("full_name") or "Candidate Name"
    story.append(Paragraph(f"<b>{name}</b>", header_style))
    story.append(HRFlowable(width="100%", color=colors.HexColor("#0B3D91"), thickness=1))
    story.append(Spacer(1, 6))

    # Contact info in one line
    contact_parts = []
    for field in ("email", "phone", "location"):
        value = candidate_data.get(field)
        if value:
            contact_parts.append(str(value))
    contact_line = " | ".join(contact_parts)
    if contact_line:
        story.append(Paragraph(contact_line, body_style))
        story.append(Spacer(1, 10))

    # ----------------------------------------------------------
    # 🧩 BODY SECTIONS
    # ----------------------------------------------------------
    for sec in SECTION_ORDER:
        content = sections.get(sec, "").strip()
        if not content:
            continue

        # Section header
        story.append(Paragraph(f"<b>{sec.title()}</b>", section_title))

        # Handle each section type
        if sec == "SKILLS":
            # Render skills in a line-separated format
            skills_text = content.replace("\n", ", ").replace("•", "").strip()
            story.append(Paragraph(skills_text, body_style))
            story.append(Spacer(1, 6))

        elif sec in ("PROJECTS", "EXPERIENCE"):
            # Bulleted list for achievements
            lines = [ln.strip(" -•") for ln in content.splitlines() if ln.strip()]
            if len(lines) == 1:
                lines = [s.strip() for s in content.split(";") if s.strip()]
            bullet_items = [
                ListItem(Paragraph(item, body_style), leftIndent=10) for item in lines
            ]
            story.append(ListFlowable(bullet_items, bulletType="bullet", leftIndent=12, bulletFontSize=8))
            story.append(Spacer(1, 6))

        else:
            # For Summary / Education / Contact sections
            text_block = Paragraph(content.replace("\n", "<br/>"), body_style)
            story.append(text_block)
            story.append(Spacer(1, 6))

        # Divider line between sections
        story.append(HRFlowable(width="90%", color=colors.lightgrey, thickness=0.4))
        story.append(Spacer(1, 6))

    # ----------------------------------------------------------
    # 📦 BUILD PDF
    # ----------------------------------------------------------
    doc.build(story)
    print(f"✅ PDF created successfully at: {output_pdf_path}")
    return output_pdf_path
